// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/auth/authdelivery/authhandler"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/auth/authdomain"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/auth/authorization"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/auth/jwt"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/auth/postgres"
	service2 "github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/auth/service"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/events/delivery/eventhandler"
	postgres2 "github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/events/postgres"
	service4 "github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/events/service"
	postgres3 "github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/media/postgres"
	service3 "github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/media/service"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/notification"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/notification/notification-domain"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/notification/service"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/shared/config"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/shared/database"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/shared/queue"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/shared/redis"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/shared/storage"
	"github.com/gofiber/fiber/v3"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp() (*AppDependencies, error) {
	configConfig := config.Load()
	db, err := database.Connect(configConfig)
	if err != nil {
		return nil, err
	}
	app := provideFiberAppWithMiddleware()
	client := storage.NewClientFromConfig(configConfig)
	redisClient, err := redis.NewClient(configConfig)
	if err != nil {
		return nil, err
	}
	enforcer, err := authorization.NewEnforcer(db, configConfig)
	if err != nil {
		return nil, err
	}
	permissionChecker := authorization.NewPermissionChecker(enforcer)
	roleManager := authorization.NewRoleManager(enforcer)
	policyManager := authorization.NewPolicyManager(enforcer)
	repository := postgres.NewPostgresRepository(db)
	taskQueue := queue.NewClient(configConfig)
	queueService := NewQueueAdapter(taskQueue)
	tokenService := jwt.NewTokenService(configConfig)
	taskEnqueuer := service.NewTaskEnqueuer(taskQueue)
	emailChannelConfig := notification.NewEmailConfig(configConfig)
	channel := service.NewEmailChannel(emailChannelConfig)
	v := notification.NewEmailChannels(channel)
	notificationService := service.NewNotificationServiceWithQueue(taskEnqueuer, v...)
	authdomainNotificationService := NewAuthNotificationAdapter(notificationService)
	serviceService := service2.NewService(repository, configConfig, redisClient, queueService, permissionChecker, roleManager, policyManager, tokenService, authdomainNotificationService, enforcer)
	domainRepository := postgres2.NewPostgresRepository(db)
	domainPermissionChecker := NewEventsPermissionAdapter(permissionChecker)
	repository2 := postgres3.NewPostgresRepository(db)
	service5 := service3.NewService(repository2, client)
	mediaService := NewEventsMediaAdapter(service5)
	service6 := service4.NewService(domainRepository, domainPermissionChecker, mediaService)
	authHandler := authhandler.NewAuthHandler(serviceService, configConfig)
	eventHandler := eventhandler.NewEventHandler(service6, enforcer)
	appDependencies := provideAppDependencies(configConfig, db, app, client, redisClient, enforcer, permissionChecker, roleManager, policyManager, serviceService, tokenService, service6, service5, authHandler, eventHandler)
	return appDependencies, nil
}

// wire.go:

// AppDependencies holds all application dependencies
type AppDependencies struct {
	Config            *config.Config
	DB                *gorm.DB
	App               *fiber.App
	StorageClient     *storage.Client
	RedisClient       *redis.Client
	Enforcer          *authorization.Enforcer
	PermissionChecker authdomain.PermissionChecker
	RoleManager       authdomain.RoleManager
	PolicyManager     authdomain.PolicyManager
	AuthTokenService  authdomain.TokenService
	Notification      notificationdomain.NotificationService
	AuthService       service2.Service
	EventsService     service4.Service
	MediaService      service3.Service
	AuthHandler       *authhandler.AuthHandler
	EventsHandler     *eventhandler.EventHandler
}
