// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/account/delivery/handler"
	postgres3 "github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/account/infrastructure/postgres"
	service4 "github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/account/service"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/auth/authdelivery/authhandler"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/auth/authdomain"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/auth/authorization"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/auth/jwt"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/auth/postgres"
	service3 "github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/auth/service"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/events/delivery/eventhandler"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/events/domain"
	postgres4 "github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/events/postgres"
	service7 "github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/events/service"
	postgres6 "github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/media/postgres"
	service5 "github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/media/service"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/notification"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/notification/notification-domain"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/notification/service"
	handler3 "github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/profile/delivery/handler"
	postgres5 "github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/profile/infrastructure/postgres"
	service6 "github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/profile/service"
	handler2 "github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/team/delivery/handler"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/team/infrastructure"
	postgres2 "github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/team/infrastructure/postgres"
	service2 "github.com/ALLAN-star-glitch/nuruvent-backend/internal/modules/team/service"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/shared/config"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/shared/database"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/shared/queue"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/shared/redis"
	"github.com/ALLAN-star-glitch/nuruvent-backend/internal/shared/storage"
	"github.com/gofiber/fiber/v3"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp() (*AppDependencies, error) {
	configConfig := config.Load()
	db, err := database.Connect(configConfig)
	if err != nil {
		return nil, err
	}
	app := provideFiberAppWithMiddleware()
	client := storage.NewClientFromConfig(configConfig)
	redisClient, err := redis.NewClient(configConfig)
	if err != nil {
		return nil, err
	}
	enforcer, err := authorization.NewEnforcer(db, configConfig)
	if err != nil {
		return nil, err
	}
	permissionChecker := authorization.NewPermissionChecker(enforcer)
	roleManager := authorization.NewRoleManager(enforcer)
	policyManager := authorization.NewPolicyManager(enforcer)
	repository := postgres.NewPostgresRepository(db)
	taskQueue := queue.NewClient(configConfig)
	queueService := NewQueueAdapter(taskQueue)
	tokenService := jwt.NewTokenService(configConfig)
	taskEnqueuer := service.NewTaskEnqueuer(taskQueue)
	emailChannelConfig := notification.NewEmailConfig(configConfig)
	channel := service.NewEmailChannel(emailChannelConfig)
	v := notification.NewEmailChannels(channel)
	notificationService := service.NewNotificationServiceWithQueue(taskEnqueuer, v...)
	authdomainNotificationService := NewAuthNotificationAdapter(notificationService)
	teamdomainRepository := postgres2.NewTeamRepository(db)
	authService := NewTeamAuthAdapter(repository)
	casbinService := NewTeamCasbinAdapter(permissionChecker, roleManager, policyManager)
	serviceNotificationService := NewTeamNotificationAdapter(notificationService)
	aiService := infrastructure.NewOpenRouterAIAdapter(configConfig)
	serviceService := service2.NewTeamService(teamdomainRepository, authService, casbinService, serviceNotificationService, aiService)
	teamService := NewAuthTeamAdapter(serviceService)
	service8 := service3.NewService(repository, configConfig, redisClient, queueService, permissionChecker, roleManager, policyManager, tokenService, authdomainNotificationService, enforcer, teamService)
	accountdomainRepository := postgres3.NewAccountRepository(db)
	serviceAuthService := NewAccountAuthAdapter(service8)
	notificationService2 := NewAccountNotificationAdapter(notificationService)
	service9 := service4.NewAccountService(accountdomainRepository, serviceAuthService, notificationService2)
	domainRepository := postgres4.NewPostgresRepository(db)
	domainPermissionChecker := NewEventsPermissionAdapter(permissionChecker)
	repository2 := postgres5.NewProfileRepository(db)
	permissionChecker2 := NewProfilePermissionAdapter(permissionChecker)
	domainRoleManager := NewProfileRoleManagerAdapter(roleManager)
	repository3 := postgres6.NewPostgresRepository(db)
	service10 := service5.NewService(repository3, client)
	mediaService := NewProfileMediaAdapter(service10)
	service11 := service6.NewProfileService(repository2, permissionChecker2, domainRoleManager, mediaService)
	userInfoProvider := NewEventsUserInfoAdapter(service11)
	domainMediaService := NewEventsMediaAdapter(service10)
	organizerProvider := provideOrganizerProvider(service9)
	service12 := service7.NewService(domainRepository, domainPermissionChecker, userInfoProvider, domainMediaService, organizerProvider)
	authHandler := authhandler.NewAuthHandler(service8, configConfig)
	accountHandler := handler.NewAccountHandler(service9)
	teamHandler := handler2.NewTeamHandler(serviceService)
	eventHandler := eventhandler.NewEventHandler(service12)
	profileHandler := handler3.NewProfileHandler(service11)
	appDependencies := provideAppDependencies(configConfig, db, app, client, redisClient, enforcer, permissionChecker, roleManager, policyManager, service8, tokenService, service9, serviceService, service12, service11, service10, notificationService, authHandler, accountHandler, teamHandler, eventHandler, profileHandler, aiService, organizerProvider)
	return appDependencies, nil
}

// wire.go:

type AppDependencies struct {
	Config            *config.Config
	DB                *gorm.DB
	App               *fiber.App
	StorageClient     *storage.Client
	RedisClient       *redis.Client
	Enforcer          *authorization.Enforcer
	PermissionChecker authdomain.PermissionChecker
	RoleManager       authdomain.RoleManager
	PolicyManager     authdomain.PolicyManager
	AuthTokenService  authdomain.TokenService
	AuthService       service3.Service
	AccountService    service4.Service
	TeamService       service2.Service
	EventsService     service7.Service
	ProfileService    service6.Service
	MediaService      service5.Service
	NotificationSvc   notificationdomain.NotificationService
	AuthHandler       *authhandler.AuthHandler
	AccountHandler    *handler.AccountHandler
	TeamHandler       *handler2.TeamHandler
	EventsHandler     *eventhandler.EventHandler
	ProfileHandler    *handler3.ProfileHandler
	AIService         service2.AIService
	OrganizerProvider domain.OrganizerProvider
}
